using System;
using System.Collections.Generic;
using System.Text;

namespace SharpBoyEmulator.Core
{
    public static class InstructionSet
    {
        public static readonly Opcode[] StandardOpcodes =
        {
            new Opcode("NOP",               0x00, 0, 4, 1,   (d, i) => { }),
            new Opcode("LD BC, {0:X4}",     0x01, 2, 12, 3,  (d, i) => d.Processor.Registers.BC = i.Parameter16),
            new Opcode("LD (BC), A",        0x02, 0, 8, 1,  (d, i) => d.Memory.WriteByte(d.Processor.Registers.BC, d.Processor.Registers.A)),
            new Opcode("INC BC",            0x03, 0, 8, 1, (d, i) => d.Processor.Registers.BC++),
            new Opcode("INC B",             0x04, 0, 4, 1, (d, i) => d.Processor.Inc(d.Processor.Registers.B)),
            new Opcode("DEC B",                0x05, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Dec(d.Processor.Registers.B)),
            new Opcode("LD B, {0:X2}",         0x06, 1, 8, 2, (d, i) => d.Processor.Registers.B = i.Parameter8),
            new Opcode("RLCA",                 0x07, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Rlc(d.Processor.Registers.A)),
            new Opcode("LD ({0:X4}), SP",      0x08, 2, 20, 3, (d, i) => d.Memory.WriteUShort(i.Parameter16, d.Processor.Registers.SP)),
            new Opcode("ADD HL, BC",           0x09, 0, 8, 1, (d, i) => d.Processor.Registers.HL = d.Processor.Add(d.Processor.Registers.HL, d.Processor.Registers.BC)),
            new Opcode("LD A, (BC)",           0x0A, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte(d.Processor.Registers.BC)),
            new Opcode("DEC BC",               0x0B, 0, 8, 1, (d, i) => d.Processor.Registers.BC--),
            new Opcode("INC C",                0x0C, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Inc(d.Processor.Registers.C)),
            new Opcode("DEC C",                0x0D, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Dec(d.Processor.Registers.C)),
            new Opcode("LD C, {0:X2}",         0x0E, 1, 8, 2, (d, i) => d.Processor.Registers.C = i.Parameter8),
            new Opcode("RRCA",                 0x0F, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Rrc(d.Processor.Registers.A)),
            new Opcode("STOP",                 0x10, 0, 4, 1, (d, i) => d.Processor.Stop()),
            new Opcode("LD DE, {0:X4}",        0x11, 2, 12, 3, (d, i) => d.Processor.Registers.DE = i.Parameter16),
            new Opcode("LD (DE), A",           0x12, 0, 8, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.DE, d.Processor.Registers.A)),
            new Opcode("INC DE",               0x13, 0, 8, 1, (d, i) => d.Processor.Registers.DE++),
            new Opcode("INC D",                0x14, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Inc(d.Processor.Registers.D)),
            new Opcode("DEC D",                0x15, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Dec(d.Processor.Registers.D)),
            new Opcode("LD D, {0:X2}",         0x16, 1, 8, 2, (d, i) => d.Processor.Registers.D = i.Parameter8),
            new Opcode("RLA",                  0x17, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Rl(d.Processor.Registers.A)),
            new Opcode("JR {0:X2}",            0x18, 1, 12, 0, (d, i) => d.Processor.Jr(1, 1, i.Parameter8, i.Opcode)),
            new Opcode("ADD HL, DE",           0x19, 0, 8, 1, (d, i) => d.Processor.Registers.HL = d.Processor.Add(d.Processor.Registers.HL, d.Processor.Registers.DE)),
            new Opcode("LD A, (DE)",           0x1A, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte(d.Processor.Registers.DE)),
            new Opcode("DEC DE",               0x1B, 0, 8, 1, (d, i) => d.Processor.Registers.DE--),
            new Opcode("INC E",                0x1C, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Inc(d.Processor.Registers.E)),
            new Opcode("DEC E",                0x1D, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Dec(d.Processor.Registers.E)),
            new Opcode("LD E, {0:X2}",         0x1E, 1, 8, 2, (d, i) => d.Processor.Registers.E = i.Parameter8),
            new Opcode("RRA",                  0x1F, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Rr(d.Processor.Registers.A)),
            new Opcode("JR NZ, {0:X2}",        0x20, 1, 12, 8, 0, (d, i) => d.Processor.Jr(d.Processor.Registers.ZFlag, 0, i.Parameter8, i.Opcode)),
            new Opcode("LD HL, {0:X4}",        0x21, 2, 12, 3, (d, i) => d.Processor.Registers.HL = i.Parameter16),
            new Opcode("LD (HL+), A",          0x22, 0, 8, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.A)),
            new Opcode("INC HL",               0x23, 0, 8, 1, (d, i) => d.Processor.Registers.HL++),
            new Opcode("INC H",                0x24, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Inc(d.Processor.Registers.H)),
            new Opcode("DEC H",                0x25, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Dec(d.Processor.Registers.H)),
            new Opcode("LD H, {0:X2}",         0x26, 1, 8, 2, (d, i) => d.Processor.Registers.H = i.Parameter8),
            new Opcode("DAA",                  0x27, 0, 4, 1, (d, i) => d.Processor.Daa()),
            new Opcode("JR Z, {0:X2}",         0x28, 1, 12, 8, 0, (d, i) => d.Processor.Jr(d.Processor.Registers.ZFlag, 1, i.Parameter8, i.Opcode)),
            new Opcode("ADD HL, HL",           0x29, 0, 8, 1, (d, i) => d.Processor.Registers.HL = d.Processor.Add(d.Processor.Registers.HL, d.Processor.Registers.HL)),
            new Opcode("LD A, (HL+)",          0x2A, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte(d.Processor.Registers.HL++)),
            new Opcode("DEC HL",               0x2B, 0, 8, 1, (d, i) => d.Processor.Registers.HL--),
            new Opcode("INC L",                0x2C, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Inc(d.Processor.Registers.L)),
            new Opcode("DEC L",                0x2D, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Dec(d.Processor.Registers.L)),
            new Opcode("LD L, {0:X2}",         0x2E, 1, 8, 2, (d, i) => d.Processor.Registers.L = i.Parameter8),
            new Opcode("CPL",                  0x2F, 0, 4, 1, (d, i) => d.Processor.Cpl()),
            new Opcode("JR NC, {0:X2}",        0x30, 1, 12, 8, 0, (d, i) => d.Processor.Jr(d.Processor.Registers.CFlag, 0, i.Parameter8, i.Opcode)),
            new Opcode("LD SP, {0:X4}",        0x31, 2, 12, 3, (d, i) => d.Processor.Registers.SP = i.Parameter16),
            new Opcode("LD (HL-), A",          0x32, 0, 8, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL--, d.Processor.Registers.A)),
            new Opcode("INC SP",               0x33, 0, 8, 1, (d, i) => d.Processor.Registers.SP++),
            new Opcode("INC (HL)",             0x34, 0, 12, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Inc(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("DEC (HL)",             0x35, 0, 12, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Dec(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("LD (HL), {0:X2}",      0x36, 1, 8, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, i.Parameter8)),
            new Opcode("SCF",                  0x37, 0, 4, 1, (d, i) => d.Processor.Scf()),
            new Opcode("JR C, {0:X2}",         0x38, 1, 12, 8, 0, (d, i) => d.Processor.Jr(d.Processor.Registers.CFlag, 1, i.Parameter8, i.Opcode)),
            new Opcode("ADD HL, SP",           0x39, 0, 8, 1, (d, i) => d.Processor.Registers.HL = d.Processor.Add(d.Processor.Registers.HL, d.Processor.Registers.SP)),
            new Opcode("LD A, (HL-)",          0x3A, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte(d.Processor.Registers.HL--)),
            new Opcode("DEC SP",               0x3B, 0, 8, 1, (d, i) => d.Processor.Registers.SP--),
            new Opcode("INC A",                0x3C, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Inc(d.Processor.Registers.A)),
            new Opcode("DEC A",                0x3D, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Dec(d.Processor.Registers.A)),
            new Opcode("LD A, {0:X2}",         0x3E, 1, 8, 2, (d, i) => d.Processor.Registers.A = i.Parameter8),
            new Opcode("CCF",                  0x3F, 0, 4, 1, (d, i) => d.Processor.Ccf()),
            new Opcode("LD B, B",              0x40, 0, 4, 1, (d, i) => { }),
            new Opcode("LD B, C",              0x41, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Registers.C),
            new Opcode("LD B, D",              0x42, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Registers.D),
            new Opcode("LD B, E",              0x43, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Registers.E),
            new Opcode("LD B, H",              0x44, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Registers.H),
            new Opcode("LD B, L",              0x45, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Registers.L),
            new Opcode("LD B, (HL)",           0x46, 0, 8, 1, (d, i) => d.Processor.Registers.B = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD B, A",              0x47, 0, 4, 1, (d, i) => d.Processor.Registers.B = d.Processor.Registers.A),
            new Opcode("LD C, B",              0x48, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Registers.B),
            new Opcode("LD C, C",              0x49, 0, 4, 1, (d, i) => { }),
            new Opcode("LD C, D",              0x4A, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Registers.D),
            new Opcode("LD C, F",              0x4B, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Registers.E),
            new Opcode("LD C, H",              0x4C, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Registers.H),
            new Opcode("LD C, L",              0x4D, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Registers.L),
            new Opcode("LD C, (HL)",           0x4E, 0, 8, 1, (d, i) => d.Processor.Registers.C = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD C, A",              0x4F, 0, 4, 1, (d, i) => d.Processor.Registers.C = d.Processor.Registers.A),
            new Opcode("LD D, B",              0x50, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Registers.B),
            new Opcode("LD D, C",              0x51, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Registers.C),
            new Opcode("LD D, D",              0x52, 0, 4, 1, (d, i) => { }),
            new Opcode("LD D, E",              0x53, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Registers.E),
            new Opcode("LD D, H",              0x54, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Registers.H),
            new Opcode("LD D, L",              0x55, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Registers.L),
            new Opcode("LD D, (HL)",           0x56, 0, 8, 1, (d, i) => d.Processor.Registers.D = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD D, A",              0x57, 0, 4, 1, (d, i) => d.Processor.Registers.D = d.Processor.Registers.A),
            new Opcode("LD E, B",              0x58, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Registers.B),
            new Opcode("LD E, C",              0x59, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Registers.C),
            new Opcode("LD E, D",              0x5A, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Registers.D),
            new Opcode("LD E, E",              0x5B, 0, 4, 1, (d, i) => { }),
            new Opcode("LD E, H",              0x5C, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Registers.H),
            new Opcode("LD E, L",              0x5D, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Registers.L),
            new Opcode("LD E, (HL)",           0x5E, 0, 8, 1, (d, i) => d.Processor.Registers.E = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD E, A",              0x5F, 0, 4, 1, (d, i) => d.Processor.Registers.E = d.Processor.Registers.A),
            new Opcode("LD H, B",              0x60, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Registers.B),
            new Opcode("LD H, C",              0x61, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Registers.C),
            new Opcode("LD H, D",              0x62, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Registers.D),
            new Opcode("LD H, E",              0x63, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Registers.E),
            new Opcode("LD H, H",              0x64, 0, 4, 1, (d, i) => { }),
            new Opcode("LD H, L",              0x65, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Registers.L),
            new Opcode("LD H, (HL)",           0x66, 0, 8, 1, (d, i) => d.Processor.Registers.H = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD H, A",              0x67, 0, 4, 1, (d, i) => d.Processor.Registers.H = d.Processor.Registers.A),
            new Opcode("LD L, B",              0x68, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Registers.B),
            new Opcode("LD L, C",              0x69, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Registers.C),
            new Opcode("LD L, D",              0x6A, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Registers.D),
            new Opcode("LD L, E",              0x6B, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Registers.E),
            new Opcode("LD L, H",              0x6C, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Registers.H),
            new Opcode("LD L, L",              0x6D, 0, 4, 1, (d, i) => { }),
            new Opcode("LD L, (HL)",           0x6E, 0, 8, 1, (d, i) => d.Processor.Registers.L = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD L, A",              0x6F, 0, 4, 1, (d, i) => d.Processor.Registers.L = d.Processor.Registers.A),
            new Opcode("LD (HL), B",           0x70, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.B)),
            new Opcode("LD (HL), C",           0x71, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.C)),
            new Opcode("LD (HL), D",           0x72, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.D)),
            new Opcode("LD (HL), E",           0x73, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.E)),
            new Opcode("LD (HL), H",           0x74, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.H)),
            new Opcode("LD (HL), L",           0x75, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.L)),
            new Opcode("HALT",                 0x76, 0, 4, 1, (d, i) => d.Processor.Halt()),
            new Opcode("LD (HL), A",           0x77, 0, 4, 1, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Registers.A)),
            new Opcode("LD A, B",              0x78, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Registers.B),
            new Opcode("LD A, C",              0x79, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Registers.C),
            new Opcode("LD A, D",              0x7A, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Registers.D),
            new Opcode("LD A, E",              0x7B, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Registers.E),
            new Opcode("LD A, H",              0x7C, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Registers.H),
            new Opcode("LD A, L",              0x7D, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Registers.L),
            new Opcode("LD A, (HL)",           0x7E, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte(d.Processor.Registers.HL)),
            new Opcode("LD A, A",              0x7F, 0, 4, 1, (d, i) => { }),
            new Opcode("ADD A, B",             0x80, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.B)),
            new Opcode("ADD A, C",             0x81, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.C)),
            new Opcode("ADD A, D",             0x82, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.D)),
            new Opcode("ADD A, E",             0x83, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.E)),
            new Opcode("ADD A, H",             0x84, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.H)),
            new Opcode("ADD A, L",             0x85, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.L)),
            new Opcode("ADD A, (HL)",          0x86, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("ADD A, A",             0x87, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Add(d.Processor.Registers.A)),
            new Opcode("ADC A, B",             0x88, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.B)),
            new Opcode("ADC A, C",             0x89, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.C)),
            new Opcode("ADC A, D",             0x8A, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.D)),
            new Opcode("ADC A, E",             0x8B, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.E)),
            new Opcode("ADC A, H",             0x8C, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.H)),
            new Opcode("ADC A, L",             0x8D, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.L)),
            new Opcode("ADC A, (HL)",          0x8E, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("ADC A, A",             0x8F, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Adc(d.Processor.Registers.A)),
            new Opcode("SUB A, B",             0x90, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.B)),
            new Opcode("SUB A, C",             0x91, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.C)),
            new Opcode("SUB A, D",             0x92, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.D)),
            new Opcode("SUB A, E",             0x93, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.E)),
            new Opcode("SUB A, H",             0x94, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.H)),
            new Opcode("SUB A, L",             0x95, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.L)),
            new Opcode("SUB A, (HL)",          0x96, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("SUB A, A",             0x97, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sub(d.Processor.Registers.A)),
            new Opcode("SBC A, B",             0x98, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.B)),
            new Opcode("SBC A, C",             0x99, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.C)),
            new Opcode("SBC A, D",             0x9A, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.D)),
            new Opcode("SBC A, E",             0x9B, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.E)),
            new Opcode("SBC A, H",             0x9C, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.H)),
            new Opcode("SBC A, L",             0x9D, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.L)),
            new Opcode("SBC A, (HL)",          0x9E, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("SBC A, A",             0x9F, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(d.Processor.Registers.A)),
            new Opcode("AND B",                0xA0, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.B)),
            new Opcode("AND C",                0xA1, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.C)),
            new Opcode("AND D",                0xA2, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.D)),
            new Opcode("AND E",                0xA3, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.E)),
            new Opcode("AND H",                0xA4, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.H)),
            new Opcode("AND L",                0xA5, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.L)),
            new Opcode("AND (HL)",             0xA6, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("AND A",                0xA7, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(d.Processor.Registers.A)),
            new Opcode("XOR B",                0xA8, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.B)),
            new Opcode("XOR C",                0xA9, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.C)),
            new Opcode("XOR D",                0xAA, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.D)),
            new Opcode("XOR E",                0xAB, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.E)),
            new Opcode("XOR H",                0xAC, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.H)),
            new Opcode("XOR L",                0xAD, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.L)),
            new Opcode("XOR (HL)",             0xAE, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("XOR A",                0xAF, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Xor(d.Processor.Registers.A)),
            new Opcode("OR B",                 0xB0, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.B)),
            new Opcode("OR C",                 0xB1, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.C)),
            new Opcode("OR D",                 0xB2, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.D)),
            new Opcode("OR E",                 0xB3, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.E)),
            new Opcode("OR H",                 0xB4, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.H)),
            new Opcode("OR L",                 0xB5, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.L)),
            new Opcode("OR (HL)",              0xB6, 0, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("OR A",                 0xB7, 0, 4, 1, (d, i) => d.Processor.Registers.A = d.Processor.Or(d.Processor.Registers.A)),
            new Opcode("CP B",                 0xB8, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.B)),
            new Opcode("CP C",                 0xB9, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.C)),
            new Opcode("CP D",                 0xBA, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.D)),
            new Opcode("CP E",                 0xBB, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.E)),
            new Opcode("CP H",                 0xBC, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.H)),
            new Opcode("CP L",                 0xBD, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.L)),
            new Opcode("CP (HL)",              0xBE, 0, 8, 1, (d, i) => d.Processor.Cp(d.Memory.ReadByte(d.Processor.Registers.HL))),
            new Opcode("CP A",                 0xBF, 0, 4, 1, (d, i) => d.Processor.Cp(d.Processor.Registers.A)),
            new Opcode("RET NZ",               0xC0, 0, 20, 8, 0, (d, i) => d.Processor.Ret(d.Processor.Registers.ZFlag, 0, i.Opcode)),
            new Opcode("POP BC",               0xC1, 0, 12, 1, (d, i) => d.Processor.Registers.BC = d.Processor.Pop()),
            new Opcode("JP NZ, {0:X4}",        0xC2, 2, 16, 12, 0, (d, i) => d.Processor.Jp(d.Processor.Registers.ZFlag, 0, i.Parameter16, i.Opcode)),
            new Opcode("JP {0:X4}",            0xC3, 2, 16, 0, (d, i) => d.Processor.Registers.PC = i.Parameter16),
            new Opcode("CALL NZ, {0:X4}",      0xC4, 2, 24, 12, 0, (d, i) => d.Processor.Call(d.Processor.Registers.ZFlag, 0, i.Parameter16, i.Opcode)),
            new Opcode("PUSH BC",              0xC5, 0, 16, 1, (d, i) => d.Processor.Push(d.Processor.Registers.BC)),
            new Opcode("ADD A, {0:X2}",        0xC6, 1, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Add(i.Parameter8)),
            new Opcode("RST 00",               0xC7, 0, 16, 0, (d, i) => d.Processor.Rst(0x00)),
            new Opcode("RET Z",                0xC8, 0, 20, 8, 0, (d, i) => d.Processor.Ret(d.Processor.Registers.ZFlag, 1, i.Opcode)),
            new Opcode("RET",                  0xC9, 0, 16, 0, (d, i) => d.Processor.Registers.PC = d.Processor.Pop()),
            new Opcode("JP Z, {0:X4}",         0xCA, 2, 16, 12, 0, (d, i) => d.Processor.Jp(d.Processor.Registers.ZFlag, 1, i.Parameter16, i.Opcode)),
            new Opcode("### PREFIX CB ###",    0xCB, 0, 4, 2, (d, i) => { }),
            new Opcode("CALL Z, {0:X4}",       0xCC, 2, 24, 12, 0, (d, i) => d.Processor.Call(d.Processor.Registers.ZFlag, 1, i.Parameter16, i.Opcode)),
            new Opcode("CALL {0:X4}",          0xCD, 2, 24, 0, (d, i) => { d.Processor.Push((ushort)(d.Processor.Registers.PC + 3)); d.Processor.Registers.PC = i.Parameter16; }),
            new Opcode("ADC A, {0:X2}",        0xCE, 1, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Adc(i.Parameter8)),
            new Opcode("RST 08",               0xCF, 0, 16, 0, (d, i) => d.Processor.Rst(0x08)),
            new Opcode("RET NC",               0xD0, 0, 20, 8, 0, (d, i) => d.Processor.Ret(d.Processor.Registers.CFlag, 0, i.Opcode)),
            new Opcode("POP DE",               0xD1, 0, 12, 1, (d, i) => d.Processor.Registers.DE = d.Processor.Pop()),
            new Opcode("JP NC, {0:X4}",        0xD2, 2, 16, 12, 0, (d, i) => d.Processor.Jp(d.Processor.Registers.CFlag, 0, i.Parameter16, i.Opcode)),
            new Opcode("ILLEGAL OPCODE",       0xD3, 0, 0, 0, (d, i) => { }),
            new Opcode("CALL NC, {0:X4}",      0xD4, 2, 24, 12, 0, (d, i) => d.Processor.Call(d.Processor.Registers.CFlag, 0, i.Parameter16, i.Opcode)),
            new Opcode("PUSH DE",              0xD5, 0, 16, 1, (d, i) => d.Processor.Push(d.Processor.Registers.DE)),
            new Opcode("SUB {0:X2}",           0xD6, 1, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Sub(i.Parameter8)),
            new Opcode("RST 10",               0xD7, 0, 16, 0, (d, i) => d.Processor.Rst(0x10)),
            new Opcode("RET C",                0xD8, 0, 20, 8, 0, (d, i) => d.Processor.Ret(d.Processor.Registers.CFlag, 1, i.Opcode)),
            new Opcode("RETI",                 0xD9, 0, 16, 0, (d, i) => { d.Processor.Registers.PC = d.Processor.Pop(); d.Processor.Registers.IME = true; }),
            new Opcode("JP C, {0:X4}",         0xDA, 2, 16, 12, 0, (d, i) => d.Processor.Jp(d.Processor.Registers.CFlag, 1, i.Parameter16, i.Opcode)),
            new Opcode("ILLEGAL OPCODE",       0xDB, 0, 0, 0, (d,i) => { }),
            new Opcode("CALL C, {0:X4}",       0xDC, 2, 24, 12, 0, (d, i) => d.Processor.Call(d.Processor.Registers.CFlag, 1, i.Parameter16, i.Opcode)),
            new Opcode("ILLEGAL OPCODE",       0xDD, 0, 0, 0, (d,i) => { }),
            new Opcode("SBC A, {0:X2}",        0xDE, 1, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Sbc(i.Parameter8)),
            new Opcode("RST 18",               0xDF, 0, 16, 0, (d, i) => d.Processor.Rst(0x18)),
            new Opcode("LDH ({0:X2}), A",      0xE0, 1, 12, 2, (d, i) => d.Memory.WriteByte((ushort)((0xFF << 8) | i.Parameter8), d.Processor.Registers.A)),
            new Opcode("POP HL",               0xE1, 0, 12, 1, (d, i) => d.Processor.Registers.HL = d.Processor.Pop()),
            new Opcode("LDH (C), A",           0xE2, 0, 8, 1, (d, i) => d.Memory.WriteByte((ushort)((0xFF << 8) | d.Processor.Registers.C), d.Processor.Registers.A)),
            new Opcode("ILLEGAL OPCODE",       0xE3, 0, 0, 0, (d,i) => { }),
            new Opcode("ILLEGAL OPCODE",       0xE4, 0, 0, 0, (d,i) => { }),
            new Opcode("PUSH HL",              0xE5, 0, 16, 1, (d, i) => d.Processor.Push(d.Processor.Registers.HL)),
            new Opcode("AND {0:X2}",           0xE6, 1, 8, 1, (d, i) => d.Processor.Registers.A = d.Processor.And(i.Parameter8)),
            new Opcode("RST 20",               0xE7, 0, 16, 0, (d, i) => d.Processor.Rst(0x20)),
            new Opcode("ADD SP, {0:X2}",       0xE8, 1, 16, 2, (d, i) => d.Processor.AddSp(i.Parameter8)),
            new Opcode("JP (HL)",              0xE9, 0, 4, 0, (d, i) => d.Processor.Registers.PC = d.Processor.Registers.HL),
            new Opcode("LD ({0:X4}), A",       0xEA, 2, 16, 3, (d, i) => d.Memory.WriteByte(i.Parameter16, d.Processor.Registers.A)),
            new Opcode("ILLEGAL OPCODE",       0xEB, 0, 0, 0, (d,i) => { }),
            new Opcode("ILLEGAL OPCODE",       0xEC, 0, 0, 0, (d,i) => { }),
            new Opcode("ILLEGAL OPCODE",       0xED, 0, 0, 0, (d,i) => { }),
            new Opcode("XOR {0:X2}",           0xEE, 1, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Xor(i.Parameter8)),
            new Opcode("RST 28",               0xEF, 0, 16, 0, (d, i) => d.Processor.Rst(0x28)),
            new Opcode("LDH A, ({0:X2})",      0xF0, 1, 12, 2, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte((ushort)((0xFF << 8) | i.Parameter8))),
            new Opcode("POP AF",               0xF1, 0, 12, 1, (d, i) => d.Processor.Registers.AF = d.Processor.Pop()),
            new Opcode("LDH A, (C)",           0xF2, 0, 8, 12, 1, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte((ushort)((0xFF << 8) | d.Processor.Registers.C))),
            new Opcode("DI",                   0xF3, 0, 4, 1, (d, i) => { d.Processor.Registers.IME = false; }),
            new Opcode("ILLEGAL OPCODE",       0xF4, 0, 0, 0, (d, i) => { }),
            new Opcode("PUSH AF",              0xF5, 0, 16, 1, (d, i) => d.Processor.Push(d.Processor.Registers.AF)),
            new Opcode("OR {0:X2}",            0xF6, 1, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Or(i.Parameter8)),
            new Opcode("RST 30",               0xF7, 0, 16, 0, (d, i) => d.Processor.Rst(0x30)),
            new Opcode("LD HD, SP + {0:X2}",   0xF8, 1, 12, 2, (d, i) => d.Processor.LdHlSpr8(i.Parameter8)),
            new Opcode("LD SP, HL",            0xF9, 0, 4, 1, (d, i) => d.Processor.Registers.SP = d.Processor.Registers.HL),
            new Opcode("LD A, ({0:X4})",       0xFA, 2, 16, 3, (d, i) => d.Processor.Registers.A = d.Memory.ReadByte(i.Parameter16)),
            new Opcode("EI",                   0xFB, 0, 0, 1, (d, i) =>  { d.Processor.Registers.IME = true; }),
            new Opcode("ILLEGAL OPCODE",       0xFC, 0, 0, 0, (d, i) => { }),
            new Opcode("ILLEGAL OPCODE",       0xFD, 0, 0, 0, (d, i) => { }),
            new Opcode("CP {0:X2}",            0xFE, 1, 8, 2, (d, i) => d.Processor.Cp(i.Parameter8)),
            new Opcode("RST 38",               0xFF, 0, 16, 0, (d, i) => d.Processor.Rst(0x38))
        };
        public static readonly Opcode[] PrefixOpcodes =
        {
            new Opcode("RLC B",                 0x00, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Rlc(d.Processor.Registers.B)),
            new Opcode("RLC C",                 0x01, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Rlc(d.Processor.Registers.C)),
            new Opcode("RLC D",                 0x02, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Rlc(d.Processor.Registers.D)),
            new Opcode("RLC E",                 0x03, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Rlc(d.Processor.Registers.E)),
            new Opcode("RLC H",                 0x04, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Rlc(d.Processor.Registers.H)),
            new Opcode("RLC L",                 0x05, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Rlc(d.Processor.Registers.L)),
            new Opcode("RLC (HL)",              0x06, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Rlc(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("RLC A",                 0x07, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Rlc(d.Processor.Registers.A)),
            new Opcode("RRC B",                 0x08, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Rrc(d.Processor.Registers.B)),
            new Opcode("RRC C",                 0x09, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Rrc(d.Processor.Registers.C)),
            new Opcode("RRC D",                 0x0A, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Rrc(d.Processor.Registers.D)),
            new Opcode("RRC E",                 0x0B, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Rrc(d.Processor.Registers.E)),
            new Opcode("RRC H",                 0x0C, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Rrc(d.Processor.Registers.H)),
            new Opcode("RRC L",                 0x0D, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Rrc(d.Processor.Registers.L)),
            new Opcode("RRC (HL)",              0x0E, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Rrc(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("RRC A",                 0x0F, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Rrc(d.Processor.Registers.A)),
            new Opcode("RL B",                  0x10, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Rl(d.Processor.Registers.B)),
            new Opcode("RL C",                  0x11, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Rl(d.Processor.Registers.C)),
            new Opcode("RL D",                  0x12, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Rl(d.Processor.Registers.D)),
            new Opcode("RL E",                  0x13, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Rl(d.Processor.Registers.E)),
            new Opcode("RL H",                  0x14, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Rl(d.Processor.Registers.H)),
            new Opcode("RL L",                  0x15, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Rl(d.Processor.Registers.L)),
            new Opcode("RL (HL)",               0x16, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Rl(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("RL A",                  0x17, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Rl(d.Processor.Registers.A)),
            new Opcode("RR B",                  0x18, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Rr(d.Processor.Registers.B)),
            new Opcode("RR C",                  0x19, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Rr(d.Processor.Registers.C)),
            new Opcode("RR D",                  0x1A, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Rr(d.Processor.Registers.D)),
            new Opcode("RR E",                  0x1B, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Rr(d.Processor.Registers.E)),
            new Opcode("RR H",                  0x1C, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Rr(d.Processor.Registers.H)),
            new Opcode("RR L",                  0x1D, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Rr(d.Processor.Registers.L)),
            new Opcode("RR (HL)",               0x1E, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Rr(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("RR A",                  0x1F, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Rr(d.Processor.Registers.A)),
            new Opcode("SLA B",                 0x20, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Sla(d.Processor.Registers.B)),
            new Opcode("SLA C",                 0x21, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Sla(d.Processor.Registers.C)),
            new Opcode("SLA D",                 0x22, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Sla(d.Processor.Registers.D)),
            new Opcode("SLA E",                 0x23, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Sla(d.Processor.Registers.E)),
            new Opcode("SLA H",                 0x24, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Sla(d.Processor.Registers.H)),
            new Opcode("SLA L",                 0x25, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Sla(d.Processor.Registers.L)),
            new Opcode("SLA (HL)",              0x26, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Sla(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("SLA A",                 0x27, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Sla(d.Processor.Registers.A)),
            new Opcode("SRA B",                 0x28, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Sra(d.Processor.Registers.B)),
            new Opcode("SRA C",                 0x29, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Sra(d.Processor.Registers.C)),
            new Opcode("SRA D",                 0x2A, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Sra(d.Processor.Registers.D)),
            new Opcode("SRA E",                 0x2B, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Sra(d.Processor.Registers.E)),
            new Opcode("SRA H",                 0x2C, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Sra(d.Processor.Registers.H)),
            new Opcode("SRA L",                 0x2D, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Sra(d.Processor.Registers.L)),
            new Opcode("SRA (HL)",              0x2E, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Sra(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("SRA A",                 0x2F, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Sra(d.Processor.Registers.A)),
            new Opcode("swap B",                0x30, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Swap(d.Processor.Registers.B)),
            new Opcode("swap C",                0x31, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Swap(d.Processor.Registers.C)),
            new Opcode("swap D",                0x32, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Swap(d.Processor.Registers.D)),
            new Opcode("swap E",                0x33, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Swap(d.Processor.Registers.E)),
            new Opcode("swap H",                0x34, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Swap(d.Processor.Registers.H)),
            new Opcode("swap L",                0x35, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Swap(d.Processor.Registers.L)),
            new Opcode("swap (HL)",             0x36, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Swap(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("swap A",                0x37, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Swap(d.Processor.Registers.A)),
            new Opcode("SRL B",                 0x38, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Srl(d.Processor.Registers.B)),
            new Opcode("SRL C",                 0x39, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Srl(d.Processor.Registers.C)),
            new Opcode("SRL D",                 0x3A, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Srl(d.Processor.Registers.D)),
            new Opcode("SRL E",                 0x3B, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Srl(d.Processor.Registers.E)),
            new Opcode("SRL H",                 0x3C, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Srl(d.Processor.Registers.H)),
            new Opcode("SRL L",                 0x3D, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Srl(d.Processor.Registers.L)),
            new Opcode("SRL (HL)",              0x3E, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Srl(d.Memory.ReadByte(d.Processor.Registers.HL)))),
            new Opcode("SRL A",                 0x3F, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Srl(d.Processor.Registers.A)),
            new Opcode("BIT 0, B",              0x40, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 0)),
            new Opcode("BIT 0, C",              0x41, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 0)),
            new Opcode("BIT 0, D",              0x42, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 0)),
            new Opcode("BIT 0, E",              0x43, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 0)),
            new Opcode("BIT 0, H",              0x44, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 0)),
            new Opcode("BIT 0, L",              0x45, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 0)),
            new Opcode("BIT 0, (HL)",           0x46, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 0)),
            new Opcode("BIT 0, A",              0x47, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 0)),
            new Opcode("BIT 1, B",              0x48, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 1)),
            new Opcode("BIT 1, C",              0x49, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 1)),
            new Opcode("BIT 1, D",              0x4A, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 1)),
            new Opcode("BIT 1, E",              0x4B, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 1)),
            new Opcode("BIT 1, H",              0x4C, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 1)),
            new Opcode("BIT 1, L",              0x4D, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 1)),
            new Opcode("BIT 1, (HL)",           0x4E, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 1)),
            new Opcode("BIT 1, A",              0x4F, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 1)),      
            new Opcode("BIT 2, B",              0x50, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 2)),
            new Opcode("BIT 2, C",              0x51, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 2)),
            new Opcode("BIT 2, D",              0x52, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 2)),
            new Opcode("BIT 2, E",              0x53, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 2)),
            new Opcode("BIT 2, H",              0x54, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 2)),
            new Opcode("BIT 2, L",              0x55, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 2)),
            new Opcode("BIT 2, (HL)",           0x56, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 2)),
            new Opcode("BIT 2, A",              0x57, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 2)),
            new Opcode("BIT 3, B",              0x58, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 3)),
            new Opcode("BIT 3, C",              0x59, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 3)),
            new Opcode("BIT 3, D",              0x5A, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 3)),
            new Opcode("BIT 3, E",              0x5B, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 3)),
            new Opcode("BIT 3, H",              0x5C, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 3)),
            new Opcode("BIT 3, L",              0x5D, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 3)),
            new Opcode("BIT 3, (HL)",           0x5E, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 3)),
            new Opcode("BIT 3, A",              0x5F, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 3)),
            new Opcode("BIT 4, B",              0x60, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 4)),
            new Opcode("BIT 4, C",              0x61, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 4)),
            new Opcode("BIT 4, D",              0x62, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 4)),
            new Opcode("BIT 4, E",              0x63, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 4)),
            new Opcode("BIT 4, H",              0x64, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 4)),
            new Opcode("BIT 4, L",              0x65, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 4)),
            new Opcode("BIT 4, (HL)",           0x66, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 4)),
            new Opcode("BIT 4, A",              0x67, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 4)),
            new Opcode("BIT 5, B",              0x68, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 5)),
            new Opcode("BIT 5, C",              0x69, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 5)),
            new Opcode("BIT 5, D",              0x6A, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 5)),
            new Opcode("BIT 5, E",              0x6B, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 5)),
            new Opcode("BIT 5, H",              0x6C, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 5)),
            new Opcode("BIT 5, L",              0x6D, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 5)),
            new Opcode("BIT 5, (HL)",           0x6E, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 5)),
            new Opcode("BIT 5, A",              0x6F, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 5)),
            new Opcode("BIT 6, B",              0x70, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 6)),
            new Opcode("BIT 6, C",              0x71, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 6)),
            new Opcode("BIT 6, D",              0x72, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 6)),
            new Opcode("BIT 6, E",              0x73, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 6)),
            new Opcode("BIT 6, H",              0x74, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 6)),
            new Opcode("BIT 6, L",              0x75, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 6)),
            new Opcode("BIT 6, (HL)",           0x76, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 6)),
            new Opcode("BIT 6, A",              0x77, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 6)),
            new Opcode("BIT 7, B",              0x78, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.B, 7)),
            new Opcode("BIT 7, C",              0x79, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.C, 7)),
            new Opcode("BIT 7, D",              0x7A, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.D, 7)),
            new Opcode("BIT 7, E",              0x7B, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.E, 7)),
            new Opcode("BIT 7, H",              0x7C, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.H, 7)),
            new Opcode("BIT 7, L",              0x7D, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.L, 7)),
            new Opcode("BIT 7, (HL)",           0x7E, 0, 16, 2, (d, i) => d.Processor.Bit(d.Memory.ReadByte(d.Processor.Registers.HL), 7)),
            new Opcode("BIT 7, A",              0x7F, 0, 8, 2, (d, i) => d.Processor.Bit(d.Processor.Registers.A, 7)),
            new Opcode("RES 0, B",              0x80, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 0)),
            new Opcode("RES 0, C",              0x81, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 0)),
            new Opcode("RES 0, D",              0x82, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 0)),
            new Opcode("RES 0, E",              0x83, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 0)),
            new Opcode("RES 0, H",              0x84, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 0)),
            new Opcode("RES 0, L",              0x85, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 0)),
            new Opcode("RES 0, (HL)",           0x86, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 0))),
            new Opcode("RES 0, A",              0x87, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 0)),
            new Opcode("RES 1, B",              0x88, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 1)),
            new Opcode("RES 1, C",              0x89, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 1)),
            new Opcode("RES 1, D",              0x8A, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 1)),
            new Opcode("RES 1, E",              0x8B, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 1)),
            new Opcode("RES 1, H",              0x8C, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 1)),
            new Opcode("RES 1, L",              0x8D, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 1)),
            new Opcode("RES 1, (HL)",           0x8E, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 1))),
            new Opcode("RES 1, A",              0x8F, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 1)),      
            new Opcode("RES 2, B",              0x90, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 2)),
            new Opcode("RES 2, C",              0x91, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 2)),
            new Opcode("RES 2, D",              0x92, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 2)),
            new Opcode("RES 2, E",              0x93, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 2)),
            new Opcode("RES 2, H",              0x94, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 2)),
            new Opcode("RES 2, L",              0x95, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 2)),
            new Opcode("RES 2, (HL)",           0x96, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 2))),
            new Opcode("RES 2, A",              0x97, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 2)),
            new Opcode("RES 3, B",              0x98, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 3)),
            new Opcode("RES 3, C",              0x99, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 3)),
            new Opcode("RES 3, D",              0x9A, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 3)),
            new Opcode("RES 3, E",              0x9B, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 3)),
            new Opcode("RES 3, H",              0x9C, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 3)),
            new Opcode("RES 3, L",              0x9D, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 3)),
            new Opcode("RES 3, (HL)",           0x9E, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 3))),
            new Opcode("RES 3, A",              0x9F, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 3)),
            new Opcode("RES 4, B",              0xA0, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 4)),
            new Opcode("RES 4, C",              0xA1, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 4)),
            new Opcode("RES 4, D",              0xA2, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 4)),
            new Opcode("RES 4, E",              0xA3, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 4)),
            new Opcode("RES 4, H",              0xA4, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 4)),
            new Opcode("RES 4, L",              0xA5, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 4)),
            new Opcode("RES 4, (HL)",           0xA6, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 4))),
            new Opcode("RES 4, A",              0xA7, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 4)),
            new Opcode("RES 5, B",              0xA8, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 5)),
            new Opcode("RES 5, C",              0xA9, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 5)),
            new Opcode("RES 5, D",              0xAA, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 5)),
            new Opcode("RES 5, E",              0xAB, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 5)),
            new Opcode("RES 5, H",              0xAC, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 5)),
            new Opcode("RES 5, L",              0xAD, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 5)),
            new Opcode("RES 5, (HL)",           0xAE, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 5))),
            new Opcode("RES 5, A",              0xAF, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 5)),
            new Opcode("RES 6, B",              0xB0, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 6)),
            new Opcode("RES 6, C",              0xB1, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 6)),
            new Opcode("RES 6, D",              0xB2, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 6)),
            new Opcode("RES 6, E",              0xB3, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 6)),
            new Opcode("RES 6, H",              0xB4, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 6)),
            new Opcode("RES 6, L",              0xB5, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 6)),
            new Opcode("RES 6, (HL)",           0xB6, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 6))),
            new Opcode("RES 6, A",              0xB7, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 6)),
            new Opcode("RES 7, B",              0xB8, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Res(d.Processor.Registers.B, 7)),
            new Opcode("RES 7, C",              0xB9, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Res(d.Processor.Registers.C, 7)),
            new Opcode("RES 7, D",              0xBA, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Res(d.Processor.Registers.D, 7)),
            new Opcode("RES 7, E",              0xBB, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Res(d.Processor.Registers.E, 7)),
            new Opcode("RES 7, H",              0xBC, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Res(d.Processor.Registers.H, 7)),
            new Opcode("RES 7, L",              0xBD, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Res(d.Processor.Registers.L, 7)),
            new Opcode("RES 7, (HL)",           0xBE, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Res(d.Memory.ReadByte(d.Processor.Registers.HL), 7))),
            new Opcode("RES 7, A",              0xBF, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Res(d.Processor.Registers.A, 7)),
            new Opcode("SET 0, B",              0xC0, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 0)),
            new Opcode("SET 0, C",              0xC1, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 0)),
            new Opcode("SET 0, D",              0xC2, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 0)),
            new Opcode("SET 0, E",              0xC3, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 0)),
            new Opcode("SET 0, H",              0xC4, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 0)),
            new Opcode("SET 0, L",              0xC5, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 0)),
            new Opcode("SET 0, (HL)",           0xC6, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 0))),
            new Opcode("SET 0, A",              0xC7, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 0)),
            new Opcode("SET 1, B",              0xC8, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 1)),
            new Opcode("SET 1, C",              0xC9, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 1)),
            new Opcode("SET 1, D",              0xCA, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 1)),
            new Opcode("SET 1, E",              0xCB, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 1)),
            new Opcode("SET 1, H",              0xCC, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 1)),
            new Opcode("SET 1, L",              0xCD, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 1)),
            new Opcode("SET 1, (HL)",           0xCE, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 1))),
            new Opcode("SET 1, A",              0xCF, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 1)),      
            new Opcode("SET 2, B",              0xD0, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 2)),
            new Opcode("SET 2, C",              0xD1, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 2)),
            new Opcode("SET 2, D",              0xD2, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 2)),
            new Opcode("SET 2, E",              0xD3, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 2)),
            new Opcode("SET 2, H",              0xD4, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 2)),
            new Opcode("SET 2, L",              0xD5, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 2)),
            new Opcode("SET 2, (HL)",           0xD6, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 2))),
            new Opcode("SET 2, A",              0xD7, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 2)),
            new Opcode("SET 3, B",              0xD8, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 3)),
            new Opcode("SET 3, C",              0xD9, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 3)),
            new Opcode("SET 3, D",              0xDA, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 3)),
            new Opcode("SET 3, E",              0xDB, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 3)),
            new Opcode("SET 3, H",              0xDC, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 3)),
            new Opcode("SET 3, L",              0xDD, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 3)),
            new Opcode("SET 3, (HL)",           0xDE, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 3))),
            new Opcode("SET 3, A",              0xDF, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 3)),
            new Opcode("SET 4, B",              0xE0, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 4)),
            new Opcode("SET 4, C",              0xE1, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 4)),
            new Opcode("SET 4, D",              0xE2, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 4)),
            new Opcode("SET 4, E",              0xE3, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 4)),
            new Opcode("SET 4, H",              0xE4, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 4)),
            new Opcode("SET 4, L",              0xE5, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 4)),
            new Opcode("SET 4, (HL)",           0xE6, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 4))),
            new Opcode("SET 4, A",              0xE7, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 4)),
            new Opcode("SET 5, B",              0xE8, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 5)),
            new Opcode("SET 5, C",              0xE9, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 5)),
            new Opcode("SET 5, D",              0xEA, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 5)),
            new Opcode("SET 5, E",              0xEB, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 5)),
            new Opcode("SET 5, H",              0xEC, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 5)),
            new Opcode("SET 5, L",              0xED, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 5)),
            new Opcode("SET 5, (HL)",           0xEE, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 5))),
            new Opcode("SET 5, A",              0xEF, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 5)),
            new Opcode("SET 6, B",              0xF0, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 6)),
            new Opcode("SET 6, C",              0xF1, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 6)),
            new Opcode("SET 6, D",              0xF2, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 6)),
            new Opcode("SET 6, E",              0xF3, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 6)),
            new Opcode("SET 6, H",              0xF4, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 6)),
            new Opcode("SET 6, L",              0xF5, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 6)),
            new Opcode("SET 6, (HL)",           0xF6, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 6))),
            new Opcode("SET 6, A",              0xF7, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 6)),
            new Opcode("SET 7, B",              0xF8, 0, 8, 2, (d, i) => d.Processor.Registers.B = d.Processor.Set(d.Processor.Registers.B, 7)),
            new Opcode("SET 7, C",              0xF9, 0, 8, 2, (d, i) => d.Processor.Registers.C = d.Processor.Set(d.Processor.Registers.C, 7)),
            new Opcode("SET 7, D",              0xFA, 0, 8, 2, (d, i) => d.Processor.Registers.D = d.Processor.Set(d.Processor.Registers.D, 7)),
            new Opcode("SET 7, E",              0xFB, 0, 8, 2, (d, i) => d.Processor.Registers.E = d.Processor.Set(d.Processor.Registers.E, 7)),
            new Opcode("SET 7, H",              0xFC, 0, 8, 2, (d, i) => d.Processor.Registers.H = d.Processor.Set(d.Processor.Registers.H, 7)),
            new Opcode("SET 7, L",              0xFD, 0, 8, 2, (d, i) => d.Processor.Registers.L = d.Processor.Set(d.Processor.Registers.L, 7)),
            new Opcode("SET 7, (HL)",           0xFE, 0, 16, 2, (d, i) => d.Memory.WriteByte(d.Processor.Registers.HL, d.Processor.Set(d.Memory.ReadByte(d.Processor.Registers.HL), 7))),
            new Opcode("SET 7, A",              0xFF, 0, 8, 2, (d, i) => d.Processor.Registers.A = d.Processor.Set(d.Processor.Registers.A, 7)),
        };
    }
}
